export const DECK_MAP_ACTION_TYPES = {
  SET_DECK_MAP: "SET_DECK_MAP",
  SET_CURRENT_PLACEMENT: "SET_CURRENT_PLACEMENT",
  SET_CURRENT_DECK_ID: "SET_CURRENT_DECK_ID",
  ADD_CARGO_PLACEMENT: "ADD_CARGO_PLACEMENT",
  SET_CARGO_PLACEMENTS: "SET_CARGO_PLACEMENTS",
  REMOVE_CARGO_PLACEMENT: "REMOVE_CARGO_PLACEMENT",
};
